{% set version = "2.37.1" %}
{% set build = 0 %}

package:
  name: git
  version: {{ version }}

source:
  - url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe  # [win64]
    folder: .  # [win64]
    sha256: b0bc403bb03326b835e239b3bf7c0af277f43eba5421132dc8531204c78b6b25  # [win64]

build:
  number: {{ build }}
  skip: True  # [not win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - 7za

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\git.exe exit 1
    - if not exist %PREFIX%\\Menu\\git-bash.json exit 1
    - if not exist %PREFIX%\\Menu\\git-bash.ico exit 1
    - git --version
    - git clone https://github.com/TuftsRT/conda-packages

about:
  home: https://github.com/TuftsRT/conda-packages
  summary: Conda-enabled Git Bash prompt with Start Menu shortcut
  license: GPL-2.0-only
