context:
  version: 2.0.0
  build_number: 0
  ci_tag: ${{ env.get("CI_TAG", default="") }}

package:
  name: idle-shortcut
  version: ${{ version }}

build:
  number: ${{ build_number }}
  skip:
    - not win
  string: >-
    ${{ hash }}_${{ build_number }}${{ '_' ~ ci_tag if ci_tag else '' }}

requirements:
  run:
    - menuinst >=2.5.0
    - python

tests:
  - script:
      - if not exist %PREFIX%\Menu\idle.json exit 1
      - if not exist %PREFIX%\Menu\idle.ico exit 1

about:
  homepage: https://github.com/TuftsRT/conda-packages
  summary: Start Menu shortcut for Python IDLE
  license: BSD-3-Clause
  license_file: LICENSE
