{% set version = "1.0" %}
{% set build = 0 %}

package:
  name: orange-shortcut
  version: {{ version }}

build:
  number: {{ build }}
  skip: True  # [not win]

requirements:
  run:
    - menuinst >=1.4.18
    - orange3

test:
  commands:
    - if not exist %PREFIX%\\Menu\\orange.json exit 1
    - if not exist %PREFIX%\\Menu\\orange.ico exit 1

about:
  home: https://github.com/TuftsRT/conda-packages
  summary: Start Menu shortcut for Orange Data Mining
  license: BSD-3-Clause
  license_file: LICENSE
