{% set version = "1.0" %}
{% set build = 0 %}

package:
  name: deeplabcut-shortcut
  version: {{ version }}

build:
  number: {{ build }}
  skip: True  # [not win]

requirements:
  run:
    - menuinst >=1.4.18

test:
  commands:
    - if not exist %PREFIX%\\Menu\\deeplabcut.json exit 1
    - if not exist %PREFIX%\\Menu\\deeplabcut.ico exit 1

about:
  home: https://github.com/TuftsRT/conda-packages
  summary: Start Menu shortcut for DeepLabCut
  license: BSD-3-Clause
  license_file: LICENSE
